-- H2 (MySQL mode) schema for local D.1
CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64),
  mobile VARCHAR(20),
  real_name VARCHAR(64),
  id_card_no VARCHAR(32),
  password_hash VARCHAR(255),
  must_change_password TINYINT NOT NULL DEFAULT 0,
  is_platform_admin TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username ON sys_user(username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_mobile ON sys_user(mobile);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_id_card ON sys_user(id_card_no);
-- 已有本地库补列（新建表时上面已含该列，重复执行可忽略）
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS must_change_password TINYINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS user_wechat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  app_id VARCHAR(64) NOT NULL,
  openid VARCHAR(64) NOT NULL,
  unionid VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_wechat_app_openid ON user_wechat(app_id, openid);

CREATE TABLE IF NOT EXISTS community (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  address VARCHAR(255),
  intro CLOB,
  cover_attachment_id BIGINT,
  contact_phone VARCHAR(32),
  has_formal_committee TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS building (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  building_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS floor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  building_id BIGINT NOT NULL,
  unit_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  floor_no INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS community_house_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  property_fee_unit_price DECIMAL(12,4),
  status TINYINT NOT NULL DEFAULT 1,
  sort_no INT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  building_id BIGINT NOT NULL,
  unit_id BIGINT NOT NULL,
  floor_id BIGINT NOT NULL,
  room_no VARCHAR(32) NOT NULL,
  house_type_id BIGINT,
  area_sqm DECIMAL(10,2),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parking_space (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  space_no VARCHAR(64) NOT NULL,
  room_id BIGINT,
  remark VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_vehicle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  plate_no VARCHAR(32) NOT NULL,
  parking_space_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_occupant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  resident_role VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  source VARCHAR(32) NOT NULL,
  approved_at TIMESTAMP,
  approved_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_community (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  staff_role VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 一人多岗：同小区同人同岗唯一。历史 PROPERTY_ADMIN（物业管理员）→ 客服 由 LegacyStaffRoleMigrateRunner 处理
CREATE UNIQUE INDEX IF NOT EXISTS uk_staff_community_role ON staff_community(community_id, user_id, staff_role);

CREATE TABLE IF NOT EXISTS committee_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS community_application (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_user_id BIGINT NOT NULL,
  applicant_name VARCHAR(64) NOT NULL,
  applicant_role VARCHAR(16) NOT NULL,
  applicant_mobile VARCHAR(20) NOT NULL,
  apply_reason VARCHAR(20),
  province_code VARCHAR(16) NOT NULL,
  province_name VARCHAR(64) NOT NULL,
  city_code VARCHAR(16) NOT NULL,
  city_name VARCHAR(64) NOT NULL,
  district_code VARCHAR(16) NOT NULL,
  district_name VARCHAR(64) NOT NULL,
  community_name VARCHAR(128) NOT NULL,
  template_code VARCHAR(32),
  status VARCHAR(16) NOT NULL,
  reject_reason VARCHAR(255),
  reviewed_by BIGINT,
  reviewed_at TIMESTAMP,
  community_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_application (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  applicant_user_id BIGINT NOT NULL,
  applicant_name VARCHAR(64) NOT NULL,
  applicant_mobile VARCHAR(20) NOT NULL,
  applicant_id_card_no VARCHAR(32),
  house_type_id BIGINT,
  apply_role VARCHAR(32) NOT NULL,
  apply_message VARCHAR(500),
  status VARCHAR(16) NOT NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'USER_APPLY',
  reject_reason VARCHAR(255),
  reviewed_by BIGINT,
  reviewed_at TIMESTAMP,
  result_occupant_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_change_application (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  applicant_user_id BIGINT NOT NULL,
  change_type VARCHAR(32) NOT NULL,
  payload_json CLOB NOT NULL,
  apply_message VARCHAR(500),
  status VARCHAR(16) NOT NULL,
  reject_reason VARCHAR(255),
  reviewed_by BIGINT,
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attachment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT,
  biz_type VARCHAR(32) NOT NULL,
  biz_id BIGINT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(128),
  size_bytes BIGINT NOT NULL,
  storage_key VARCHAR(512) NOT NULL,
  url VARCHAR(512),
  uploaded_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_batch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL,
  success_count INT NOT NULL DEFAULT 0,
  fail_count INT NOT NULL DEFAULT 0,
  fail_detail_json CLOB,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT,
  actor_id BIGINT NOT NULL,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(64),
  target_id BIGINT,
  detail_json CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscribe_notify_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT,
  user_id BIGINT NOT NULL,
  scene VARCHAR(64) NOT NULL,
  template_id VARCHAR(128),
  status VARCHAR(16) NOT NULL,
  error_msg VARCHAR(512),
  biz_type VARCHAR(32),
  biz_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todo_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT,
  user_id BIGINT NOT NULL,
  todo_type VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(500),
  biz_type VARCHAR(32),
  biz_id BIGINT,
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  read_at TIMESTAMP,
  done_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- ========== D.2～D.4 ==========

CREATE TABLE IF NOT EXISTS fee_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  fee_category VARCHAR(32) NOT NULL,
  calc_type VARCHAR(32) NOT NULL,
  monthly_amount DECIMAL(12,2),
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fee_item_price_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  fee_item_id BIGINT NOT NULL,
  match_key VARCHAR(64) NOT NULL,
  unit_price DECIMAL(12,4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_fee_price ON fee_item_price_rule(fee_item_id, match_key);

CREATE TABLE IF NOT EXISTS room_fee_exemption (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  fee_category VARCHAR(32) NOT NULL,
  fee_item_id BIGINT,
  effective_from CHAR(7) NOT NULL,
  effective_to CHAR(7),
  reason VARCHAR(255),
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_room_fee_ex_room ON room_fee_exemption(community_id, room_id);

CREATE TABLE IF NOT EXISTS fee_exemption_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  bill_month CHAR(7) NOT NULL,
  bill_id BIGINT,
  exemption_id BIGINT,
  fee_category VARCHAR(32) NOT NULL,
  fee_item_id BIGINT,
  title VARCHAR(128) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bill_meter_upload (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  bill_month CHAR(7) NOT NULL,
  fee_category VARCHAR(32) NOT NULL,
  meter_start DECIMAL(14,4),
  meter_end DECIMAL(14,4),
  unit_price DECIMAL(12,4),
  amount DECIMAL(12,2) NOT NULL,
  batch_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bill (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  bill_month CHAR(7) NOT NULL,
  status VARCHAR(16) NOT NULL,
  due_date DATE,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  pay_channel VARCHAR(32),
  paid_at TIMESTAMP,
  confirmed_by BIGINT,
  wechat_transaction_id VARCHAR(64),
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_bill_room_month ON bill(community_id, room_id, bill_month);

CREATE TABLE IF NOT EXISTS bill_line (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id BIGINT NOT NULL,
  fee_category VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  snapshot_json CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  bill_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  payer_user_id BIGINT,
  amount DECIMAL(12,2) NOT NULL,
  pay_channel VARCHAR(32) NOT NULL,
  confirmed_by BIGINT,
  paid_at TIMESTAMP NOT NULL,
  remark VARCHAR(512),
  fee_type_label VARCHAR(256),
  fee_categories VARCHAR(256),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  guide_text VARCHAR(2000),
  qr_attachment_id BIGINT,
  prepaid_enabled TINYINT NOT NULL DEFAULT 0,
  prepaid_guide_text VARCHAR(2000),
  updated_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_config_community ON payment_config(community_id);
ALTER TABLE payment_config ADD COLUMN IF NOT EXISTS prepaid_enabled TINYINT NOT NULL DEFAULT 0;
ALTER TABLE payment_config ADD COLUMN IF NOT EXISTS prepaid_guide_text VARCHAR(2000);
ALTER TABLE payment_record ADD COLUMN IF NOT EXISTS fee_type_label VARCHAR(256);
ALTER TABLE payment_record ADD COLUMN IF NOT EXISTS fee_categories VARCHAR(256);

CREATE TABLE IF NOT EXISTS prepaid_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_prepaid_room ON prepaid_account(community_id, room_id);

CREATE TABLE IF NOT EXISTS prepaid_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  entry_type VARCHAR(16) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  balance_after DECIMAL(12,2) NOT NULL,
  bill_id BIGINT,
  pay_channel VARCHAR(32),
  operator_user_id BIGINT,
  remark VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prepaid_ledger_room ON prepaid_ledger(community_id, room_id);

-- 方案 A：预缴协议（约定月份+费项；折扣=原价−实付；出账跳过；公开按账期结转 cash）
CREATE TABLE IF NOT EXISTS prepaid_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  list_amount DECIMAL(12,2) NOT NULL,
  cash_amount DECIMAL(12,2) NOT NULL,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL,
  pay_channel VARCHAR(32),
  remark VARCHAR(512),
  confirmed_by BIGINT,
  confirmed_at TIMESTAMP,
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prepaid_plan_room ON prepaid_plan(community_id, room_id);

CREATE TABLE IF NOT EXISTS prepaid_plan_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id BIGINT NOT NULL,
  community_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  bill_month CHAR(7) NOT NULL,
  fee_category VARCHAR(32) NOT NULL,
  list_amount DECIMAL(12,2) NOT NULL,
  cash_amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prepaid_plan_item_plan ON prepaid_plan_item(plan_id);
CREATE INDEX IF NOT EXISTS idx_prepaid_plan_item_cover ON prepaid_plan_item(community_id, room_id, bill_month, fee_category);

CREATE TABLE IF NOT EXISTS finance_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  entry_type VARCHAR(16) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  occur_date DATE NOT NULL,
  category VARCHAR(64),
  title VARCHAR(128) NOT NULL,
  remark VARCHAR(512),
  status VARCHAR(16) NOT NULL,
  created_by BIGINT NOT NULL,
  approved_by BIGINT,
  approved_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public_revenue_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  occur_month CHAR(7),
  remark VARCHAR(512),
  status VARCHAR(32) NOT NULL,
  submitted_by BIGINT NOT NULL,
  confirmed_by BIGINT,
  confirmed_at TIMESTAMP,
  reject_reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  content CLOB NOT NULL,
  notice_type VARCHAR(32) NOT NULL,
  urgency TINYINT NOT NULL DEFAULT 0,
  visibility VARCHAR(32) NOT NULL,
  effective_at TIMESTAMP,
  expire_at TIMESTAMP,
  created_by BIGINT NOT NULL,
  creator_identity VARCHAR(16) NOT NULL,
  cover_attachment_id BIGINT,
  show_on_banner TINYINT NOT NULL DEFAULT 0,
  banner_order INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

-- 报事报修统一为单表 service_ticket（迁移：删除旧的 repair_order / repair_reply / repair_dispatch / complaint）
DROP TABLE IF EXISTS repair_reply;
DROP TABLE IF EXISTS repair_dispatch;
DROP TABLE IF EXISTS repair_order;
DROP TABLE IF EXISTS complaint;

CREATE TABLE IF NOT EXISTS service_ticket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  node_type VARCHAR(16) NOT NULL,
  kind VARCHAR(16),
  community_id BIGINT NOT NULL,
  room_id BIGINT,
  applicant_user_id BIGINT,
  contact_name VARCHAR(64),
  contact_mobile VARCHAR(20),
  category VARCHAR(32),
  location VARCHAR(128),
  content VARCHAR(1000),
  status VARCHAR(32),
  assignee_role VARCHAR(32),
  assignee_user_id BIGINT,
  handler_user_id BIGINT,
  rating TINYINT,
  rating_comment VARCHAR(255),
  action VARCHAR(20),
  from_user_id BIGINT,
  to_user_id BIGINT,
  author_user_id BIGINT,
  to_role VARCHAR(32),
  remark VARCHAR(500),
  assigned_at TIMESTAMP,
  first_reply_at TIMESTAMP,
  escalated_to_manager TINYINT NOT NULL DEFAULT 0,
  auto_completed TINYINT NOT NULL DEFAULT 0,
  completed_at TIMESTAMP,
  replied_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- 评价维度：是否处理完成(0/1)、响应及时度、处理及时情况、处理满意情况（1~5）
ALTER TABLE service_ticket ADD COLUMN IF NOT EXISTS rating_resolved TINYINT;
ALTER TABLE service_ticket ADD COLUMN IF NOT EXISTS rating_response TINYINT;
ALTER TABLE service_ticket ADD COLUMN IF NOT EXISTS rating_handling TINYINT;
ALTER TABLE service_ticket ADD COLUMN IF NOT EXISTS rating_satisfaction TINYINT;
CREATE INDEX IF NOT EXISTS idx_ticket_parent ON service_ticket(parent_id);
CREATE INDEX IF NOT EXISTS idx_ticket_community ON service_ticket(community_id);
CREATE INDEX IF NOT EXISTS idx_ticket_kind ON service_ticket(kind);

CREATE TABLE IF NOT EXISTS vote (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  background CLOB NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_by BIGINT NOT NULL,
  creator_role VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vote_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id BIGINT NOT NULL,
  option_text VARCHAR(128) NOT NULL,
  sort_no INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vote_ballot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  voter_user_id BIGINT NOT NULL,
  option_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_vote_room ON vote_ballot(vote_id, room_id);

-- drop legacy ownership (existing H2 files)
ALTER TABLE parking_space DROP COLUMN IF EXISTS ownership;
ALTER TABLE notice ADD COLUMN IF NOT EXISTS cover_attachment_id BIGINT;
ALTER TABLE notice ADD COLUMN IF NOT EXISTS show_on_banner TINYINT NOT NULL DEFAULT 0;
ALTER TABLE notice ADD COLUMN IF NOT EXISTS banner_order INT;

-- 平台「关于我们」单页
CREATE TABLE IF NOT EXISTS about_us (
  id BIGINT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  content CLOB,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 巡检：位置挂在「单元下的楼层」；计划由经理/客服发布；一线岗扫码执行
CREATE TABLE IF NOT EXISTS inspect_spot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  building_id BIGINT NOT NULL,
  unit_id BIGINT,
  floor_id BIGINT,
  name VARCHAR(64) NOT NULL,
  categories VARCHAR(128) NOT NULL,
  req_safety CLOB,
  req_cleaning CLOB,
  req_facility CLOB,
  req_landscape CLOB,
  qr_token VARCHAR(40) NOT NULL,
  sort_no INT NOT NULL DEFAULT 0,
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_inspect_spot_token ON inspect_spot(qr_token);
CREATE INDEX IF NOT EXISTS idx_inspect_spot_floor ON inspect_spot(community_id, floor_id);
-- 已有库：单元/楼层可空（仅楼栋必填）
ALTER TABLE inspect_spot ALTER COLUMN unit_id SET NULL;
ALTER TABLE inspect_spot ALTER COLUMN floor_id SET NULL;

CREATE TABLE IF NOT EXISTS inspect_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  freq_unit VARCHAR(16) NOT NULL,
  freq_times INT NOT NULL DEFAULT 1,
  ordered TINYINT NOT NULL DEFAULT 0,
  requirement_note CLOB,
  executor_roles VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inspect_plan_spot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id BIGINT NOT NULL,
  spot_id BIGINT NOT NULL,
  sort_no INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_inspect_plan_spot ON inspect_plan_spot(plan_id);

CREATE TABLE IF NOT EXISTS inspect_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  seq_no INT NOT NULL DEFAULT 1,
  status VARCHAR(16) NOT NULL,
  assignee_user_id BIGINT,
  claimed_at TIMESTAMP,
  done_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inspect_job_plan ON inspect_job(plan_id, status);

CREATE TABLE IF NOT EXISTS inspect_visit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id BIGINT NOT NULL,
  job_id BIGINT NOT NULL,
  spot_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  note VARCHAR(500),
  photo_attachment_id BIGINT,
  scanned_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_inspect_visit_job_spot ON inspect_visit(job_id, spot_id);

